test:
  image: python:3.12
  stage: test
  before_script:
    - python -V               # Print out python version for debugging
    - pip install virtualenv  # Pip's cache doesn't store the python packages
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install pytest coverage
    - apt update && apt install -y  musl-dev libc-dev  libgl1 ffmpeg  libgl1 libglx-mesa0 xvfb  libglu1-mesa libxi-dev libxmu-dev libglu1-mesa-dev libxinerama-dev
  script:
    - python -m coverage run -m pytest --junitxml=report.xml
  after_script:
    - pip install coverage
    - coverage xml
    - coverage html
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov/
    expire_in: 2 weeks
  cache:
    key:
        files:
          - requirements.txt
    paths:
      - .cache/pip
  variables: # Change pip's cache directory to be inside the project directory because we can only cache local items.
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# deploy coverage report
pages:
  image: python:3.12
  stage: deploy
  rules:
    - when: always
      if: $CI_COMMIT_BRANCH == "main"
  dependencies:
    - test
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public/

