test:
  image: python:3.12
  stage: test
  before_script:
    - python -V               # Print out python version for debugging
    - pip install virtualenv  # Pip's cache doesn't store the python packages
    - virtualenv venv
    - source venv/bin/activate
    # libblas-dev liblapack-dev are dependencies of petsc
    # openmpi-bin libopenmpi-dev are for openmpi
    - apt update && apt install -y  musl-dev libc-dev  libgl1 ffmpeg  libgl1 libglx-mesa0 xvfb  libglu1-mesa libxi-dev libxmu-dev libglu1-mesa-dev libxinerama-dev libblas-dev liblapack-dev openmpi-bin libopenmpi-dev
    - pip install -r requirements.txt --extra-index-url https://gitlab-ci-token:${CI_JOB_TOKEN}@git.rwth-aachen.de/api/v4/projects/102532/packages/pypi/simple
    - pip install pytest coverage
  script:
    - python -m coverage run -m pytest --junitxml=report.xml
  after_script:
    - pip install coverage
    - coverage xml
    - coverage html
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov/
    expire_in: 2 weeks
  cache:
    key:
        files:
          - requirements.txt
    paths:
      - .cache/pip
  variables: # Change pip's cache directory to be inside the project directory because we can only cache local items.
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# deploy coverage report & pages
pages:
  image: python:3.12
  stage: deploy
  variables:
    PAGES_PREFIX: "" # No prefix by default (main)
  pages:  # specifies that this is a Pages job and publishes the default public directory
    path_prefix: "$PAGES_PREFIX"
  environment:
    name: "Pages ${PAGES_PREFIX}"
    url: $CI_PAGES_URL
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run on default branch (with default PAGES_PREFIX)
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Conditionally change the prefix for Merge Requests
      when: manual # Run pages manually on Merge Requests
      variables:
        PAGES_PREFIX: 'mr-$CI_MERGE_REQUEST_IID' # Prefix with the mr-<iid>, like `mr-123`
  dependencies:
    - test
  before_script:
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client git -y )'
    ## Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    ## Give the right permissions, otherwise ssh-add will refuse to add files
    ## Add the SSH key stored in SSH_PRIVATE_KEY file type CI/CD variable to the agent store
    - chmod 400 "$GITHUB_DOCS_DEPLOY_KEY"
    - ssh-add "$GITHUB_DOCS_DEPLOY_KEY"
    ## Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git config --global user.name "CI"
    - git config --global user.email "ci@wbgeo.github.io"
  script:
    # add __init__.py files, required for docs
    - find core -type d -exec touch {}/__init__.py \;
    - pip install mkdocs-material mkdocstrings[python] mkdocs-gen-files mkdocs-literate-nav
    - mkdocs build --site-dir public
    - mkdir -p htmlcov # create folder, if test did not run (on a MR)
    - mv htmlcov/ public/coverage
    # mirror to github
    - mkdir gh-pages
    - cd gh-pages
    - git init
    - git remote add origin "git@github.com:WBGeo/wbgeo.github.io.git"
    - git fetch --depth=1 origin gh-pages || true
    - git checkout --orphan gh-pages
    # cleanup old
    - git rm -rf . || true
    # copy docs & add
    - cp -r ../public/. .
    - git add .
    - git commit -m "Deploy ${CI_COMMIT_SHA}"
    - git push --force origin gh-pages
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.cache/
  artifacts:
    paths:
      - public/

