# This file is used to define the website
site_name: WBGeo
site_url: https://wbgeo.pages.rwth-aachen.de/codebase
repo_url: https://git.rwth-aachen.de/wbgeo
theme:
  name: material
  logo: 'fontawesome/solid/desktop'
  features:
    - navigation.instant
    - search.highlight
    - search.suggest
    - navigation.indexes
    - navigation.footer
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search:
  - mkdocstrings:
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
nav:
  - index.md
  - Installation Guide:
    - installation/index.md
    - Visual Editor: installation/visual.md
    - Codebase: installation/codebase.md
  - Components:
      - components/index.md
      - Data Loading: components/data_loading/index.md
      - Structural Modeling: components/structural_modeling/Manual_structural_modeling.md
      - Meshing: components/meshing/index.md
      - Process Simulation: components/simulation/Manual_simulation.md
      - Visualization: components/visualization/index.md
  - Developer's Guide:
      - developers/index.md
      - Installation: developers/installation.md
      - Components: developers/components.md
      - Types: developers/types.md
      - Local execution: developers/local.md
  - Code Reference: reference/
  - Examples: Examples.md
  - Publications: Publications.md

copyright: '(c) https://git.rwth-aachen.de/wbgeo/'
