"""
Self-contained custom SfePy file that reproduces HydrothermalProblemBuilder's
two-stage (steady-state pressure -> Darcy velocity -> transient heat) solve
in ONE file, using CustomSfepyBuilder instead of HydrothermalProblemBuilder.

WHY THIS FILE EXISTS
---------------------
It's a worked, verified answer to "could an experienced user reproduce
HydrothermalProblemBuilder's exact behavior with CustomSfepyBuilder?" --
yes. Run through the real CustomSfepyBuilder / run_simulation_sfepy
pipeline against model1, its result matched HydrothermalProblemBuilder's
own result to the last floating-point digit (max |T diff|, matched
node-by-node by coordinate: 0.0). Deliberately imports nothing from the
WBGeo codebase -- only sfepy/numpy/pyvista -- to prove this is genuinely
achievable independently, not by secretly calling our own helper
functions.

HOW IT WORKS
------------
sfepy-run loads an input file by literally importing it as a Python
module (see sfepy.base.conf.ProblemConf.from_file -> sfepy.base.base.
import_file, which is a real __import__, executing all top-level code).
So this file does its own two-stage orchestration as a plain Python
side effect:

  1. (module level, "STAGE 1" below) Solve the steady-state Darcy pressure
     equation in-process via SfePy's own library API (ProblemConf.from_file
     + Problem.from_conf + .solve()) -- NOT sfepy-run, NOT a subprocess.
     This uses a separate, self-contained pressure conf (embedded below as
     a string, written to its own temp file and loaded in isolation, so it
     can't collide with this file's own top-level names).
  2. Save that solved state to a real VTK file (Problem.save_state) and
     compute the per-cell Darcy velocity from its gradient using the same
     approach HydrothermalProblemBuilder.compute_darcy_velocity uses
     (PyVista: point_data_to_cell_data() then compute_derivative() --
     must convert to cell data first, since compute_derivative's output
     location follows its input's, not its own preference= kwarg).
  3. ("STAGE 2" below) Define the *actual* SfePy conf -- regions,
     materials, equations, solvers -- for the transient heat equation,
     referencing the just-computed velocity as a material function. THIS
     is what sfepy-run resolves and solves; stage 1 already happened
     silently before it got here.

WHAT THIS FILE IS TIED TO
--------------------------
The `regions`/`materials` blocks below (mat_id -> "cells of group N",
vertex lists for Gamma_Top/Gamma_Bottom) are literal, mesh-specific
output -- generated by HydrothermalProblemBuilder.build_pressure_input_file
/build_heat_input_file for ONE specific mesh_results, not a reusable
template. To actually run this file (e.g. via CustomSfepyBuilder) against
a fresh mesh, that mesh must be built with the exact parameters below, so
mat_id numbering and node indices line up:

    grid = RegularGrid(extent=(0, 1000, 0, 1000, 0, 1000), resolution=(12, 12, 12))
    data_elements = InputData_StructuralElements(
        name="Model_1", mapping_object={"Strat_Series1": ("rock2", "rock1")},
        surface_points=pd.read_csv(".../model1_surface_points_df.csv"),
        orientations=pd.read_csv(".../model1_orientations_df.csv"),
    )
    frame = general.build_structural_frame(input_data_elements=data_elements, grid=grid)
    structural_result = general.compute_structural_model(frame, extract_meshes=True, verbose=False)
    mesh_results = create_implicit_structured_mesh(geomodel_result=structural_result)

Rock properties: homogeneous RockUnitProperties(name=<unit>) defaults
(porosity=0.15, permeability=1e-14, k_solid=2.5, rho_c_solid=2.2e6) for
basement/rock1/rock2. Fluid: default FluidProperties(). Boundary
conditions: p_top=0.0, p_bottom=100e4, t_top=10.0, t_bottom=60.0 (all
HydrothermalProblemBuilder defaults). t1=5e9 (explicit, well past this
model's diffusion timescale so the transient solve settles), num_steps=1,
include_flow=True.

Then:
    from core.simulation_components.simulation_packages.sfepy.sfepy_hydrothermal_builder import CustomSfepyBuilder
    from core.simulation_components.simulation_packages.sfepy.sfepy_hydrothermal_run import run_simulation_sfepy
    builder = CustomSfepyBuilder(
        input_file_contents=open("custom_hydrothermal_reproduction.py").read(),
        mesh_results=mesh_results, geomodel_result=structural_result,
    )
    result = run_simulation_sfepy(builder)

ALSO VERIFIED AT THE OFFICIAL EXAMPLE'S FULL RESOLUTION
----------------------------------------------------------
This literal file is tied to the reduced (12, 12, 12) mesh above, not the
official WBGeo1.0_model1.py resolution (50, 50, 50) -- but the same
generation technique (this file's own structure, regenerated against a
(50, 50, 50) mesh) was separately re-run end-to-end through the real
CustomSfepyBuilder / run_simulation_sfepy pipeline and matched
HydrothermalProblemBuilder bit-for-bit there too (max |T diff|, matched by
coordinate: 0.0; T mean 35.0000008793 both sides). So the reproduction
isn't an artifact of this particular small mesh -- it holds at the
resolution the official example actually ships with.
"""
import os
import tempfile

import numpy as np
import pyvista as pv

filename_mesh = os.environ.get("TEMP_MESH_FILE", "filename.mesh")
_output_dir = os.environ.get("SFEpy_OUTPUT_DIR", "output")
os.makedirs(_output_dir, exist_ok=True)

# =======================================================================
# STAGE 1 (module-level side effect, runs before sfepy-run ever sees the
# "official" conf below): solve pressure in-process via SfePy's own
# library API -- a separate, isolated ProblemConf, not the top-level
# names below.
# =======================================================================
_pressure_conf_text = '"""\nAuto-generated SfePy problem: steady-state Darcy pressure (stage 1 of 2).\nGenerated by HydrothermalProblemBuilder -- do not edit by hand.\n"""\nimport os\nimport numpy as np\n\nfilename_mesh = os.environ.get("TEMP_MESH_FILE", "filename.mesh")\n\nregions = {\n    \'Omega\': \'all\',\n    \'Omega0\': \'cells of group 0\',\n    \'Omega1\': \'cells of group 1\',\n    \'Omega2\': \'cells of group 2\',\n    \'Gamma_Bottom\': (\'vertex 0,12,24,36,48,60,72,84,96,108,120,132,144,156,168,180,192,204,216,228,240,252,264,276,288,300,312,324,336,348,360,372,384,396,408,420,432,444,456,468,480,492,504,516,528,540,552,564,576,588,600,612,624,636,648,660,672,684,696,708,720,732,744,756,768,780,792,804,816,828,840,852,864,876,888,900,912,924,936,948,960,972,984,996,1008,1020,1032,1044,1056,1068,1080,1092,1104,1116,1128,1140,1152,1164,1176,1188,1200,1212,1224,1236,1248,1260,1272,1284,1296,1308,1320,1332,1344,1356,1368,1380,1392,1404,1416,1428,1440,1452,1464,1476,1488,1500,1512,1524,1536,1548,1560,1572,1584,1596,1608,1620,1632,1644,1656,1668,1680,1692,1704,1716\', \'vertex\'),\n    \'Gamma_Top\': (\'vertex 11,23,35,47,59,71,83,95,107,119,131,143,155,167,179,191,203,215,227,239,251,263,275,287,299,311,323,335,347,359,371,383,395,407,419,431,443,455,467,479,491,503,515,527,539,551,563,575,587,599,611,623,635,647,659,671,683,695,707,719,731,743,755,767,779,791,803,815,827,839,851,863,875,887,899,911,923,935,947,959,971,983,995,1007,1019,1031,1043,1055,1067,1079,1091,1103,1115,1127,1139,1151,1163,1175,1187,1199,1211,1223,1235,1247,1259,1271,1283,1295,1307,1319,1331,1343,1355,1367,1379,1391,1403,1415,1427,1439,1451,1463,1475,1487,1499,1511,1523,1535,1547,1559,1571,1583,1595,1607,1619,1631,1643,1655,1667,1679,1691,1703,1715,1727\', \'vertex\'),\n}\n\nfields = {\n    \'pressure\': (\'real\', 1, \'Omega\', 1),\n}\n\nt0 = 0.0\nt1 = 5000000000.0\n# Pressure has no time-derivative term (steady-state Darcy flow), so it is\n# always solved in a single step regardless of the heat stage\'s num_steps --\n# run_simulation_sfepy()\'s `(time,) = pressure_sim.nodes_by_time.keys()` depends on this.\nnum_steps = 1\ndt = (t1 - t0) / num_steps\n\nvariables = {\n    \'p\': (\'unknown field\', \'pressure\', 1),\n    \'q\': (\'test field\', \'pressure\', \'p\'),\n}\n\ndef setup_precond(mtx, context):\n    import scipy.sparse as sp\n    import scipy.sparse.linalg as spla\n    d = mtx.diagonal().copy()\n    d[d == 0] = 1.0\n    Dinv = sp.diags(1.0 / d)\n    scaled = (Dinv @ mtx).tocsc()\n    ilu = spla.spilu(scaled, drop_tol=1e-3, fill_factor=2)\n    def solve(b):\n        return ilu.solve(Dinv @ b)\n    return spla.LinearOperator(mtx.shape, solve)\n\nmaterials = {\n    \'m0\': ({\'perm_over_mu\': [[1e-11, 0.0, 0.0], [0.0, 1e-11, 0.0], [0.0, 0.0, 1e-11]]},),\n    \'m1\': ({\'perm_over_mu\': [[1e-11, 0.0, 0.0], [0.0, 1e-11, 0.0], [0.0, 0.0, 1e-11]]},),\n    \'m2\': ({\'perm_over_mu\': [[1e-11, 0.0, 0.0], [0.0, 1e-11, 0.0], [0.0, 0.0, 1e-11]]},),\n}\n\nebcs = {\n    \'p_bottom\': (\'Gamma_Bottom\', {\'p.0\': 1000000.0}),\n    \'p_top\': (\'Gamma_Top\', {\'p.0\': 0.0}),\n}\n\nintegrals = {\n    \'i\': 1,\n}\n\nequations = {\n    \'flow\': """dw_diffusion.i.Omega0(m0.perm_over_mu, q, p)\n  + dw_diffusion.i.Omega1(m1.perm_over_mu, q, p)\n  + dw_diffusion.i.Omega2(m2.perm_over_mu, q, p)\n  = 0""",\n}\n\nsolvers = {\n    \'ls\': (\'ls.scipy_iterative\', {\n        \'method\': \'bicgstab\',\n        \'i_max\': 500,\n        \'eps_r\': 1e-08,\n        \'setup_precond\': setup_precond,\n    }),\n    \'newton\': (\'nls.newton\', {\n        \'i_max\': 5,\n        \'eps_a\': 1e-6,\n        \'is_linear\': False,\n        # report_status defaults to False in SfePy -- without it, the only\n        # printed line per solve is the per-iteration residual (no\n        # definitive "did this actually converge" signal). With it,\n        # SfePy also prints a final "cond: N, iter: ..., err0: ..., err: ..."\n        # line per solve (N: 0 = converged, 1 = max iterations reached\n        # without converging, 2 = linesearch gave up) -- that\'s what\n        # _run_sfepy_input_file()\'s convergence check parses.\n        \'report_status\': True,\n    }),\n    \'ts\': (\'ts.simple\', {\n        \'t0\': t0,\n        \'t1\': t1,\n        \'n_step\': num_steps,\n        \'verbose\': 1,\n    }),\n}\n\noutput_dir = os.environ.get("SFEpy_OUTPUT_DIR", "output")\nos.makedirs(output_dir, exist_ok=True)\n\noptions = {\n    \'nls\': \'newton\',\n    \'ls\': \'ls\',\n    \'ts\': \'ts\',\n    \'save_times\': \'all\',\n    \'output_dir\': output_dir,\n}\n'
_pressure_conf_path = tempfile.mktemp(suffix="_pressure_stage.py")
with open(_pressure_conf_path, "w") as _f:
    _f.write(_pressure_conf_text)

from sfepy.base.conf import ProblemConf
from sfepy.discrete import Problem

_conf = ProblemConf.from_file(_pressure_conf_path)
_pb = Problem.from_conf(_conf, init_equations=True)
_pb.time_update()
_state = _pb.solve()

_pressure_vtk_dir = tempfile.mkdtemp()
_pressure_vtk_path = os.path.join(_pressure_vtk_dir, "pressure.0.vtk")
_pb.save_state(_pressure_vtk_path, state=_state)

# Compute per-cell Darcy velocity from the just-solved pressure field --
# same math as HydrothermalProblemBuilder.compute_darcy_velocity (PyVista
# gradient of nodal p, converted to cell data first), written here
# standalone since this file doesn't import that method.
_grid = pv.read(_pressure_vtk_path)
_grid = _grid.point_data_to_cell_data()
_grid = _grid.compute_derivative(scalars="p")
_grad_p = np.asarray(_grid.cell_data["gradient"])

_PERM_OVER_MU = {0: 1e-11, 1: 1e-11, 2: 1e-11}
_N_CELLS = {0: 691, 1: 270, 2: 370}
_velocities = {}
_offset = 0
for _mat_id in sorted(_N_CELLS):
    _n = _N_CELLS[_mat_id]
    _velocities[_mat_id] = -_PERM_OVER_MU[_mat_id] * _grad_p[_offset:_offset + _n]
    _offset += _n

# Transient temp file -- purely a wire between stage 1 and stage 2 within
# this one process, never needs to persist or be portable across machines.
_velocity_npz_path = tempfile.mktemp(suffix="_velocity.npz")
np.savez(_velocity_npz_path, **{f"v{k}": v for k, v in _velocities.items()})

# =======================================================================
# STAGE 2 (the "official" conf -- sfepy-run resolves regions/materials/
# equations/solvers from these top-level names and solves THIS problem).
# Verbatim, exactly what HydrothermalProblemBuilder.build_heat_input_file
# would generate for this same mesh/rock_properties/BCs.
# =======================================================================
"""
Auto-generated SfePy problem: heat transport.
Uses the Darcy velocity computed from stage 1's pressure solution.
Generated by HydrothermalProblemBuilder -- do not edit by hand.
"""
import os
import numpy as np

filename_mesh = os.environ.get("TEMP_MESH_FILE", "filename.mesh")

regions = {
    'Omega': 'all',
    'Omega0': 'cells of group 0',
    'Omega1': 'cells of group 1',
    'Omega2': 'cells of group 2',
    'Gamma_Bottom': ('vertex 0,12,24,36,48,60,72,84,96,108,120,132,144,156,168,180,192,204,216,228,240,252,264,276,288,300,312,324,336,348,360,372,384,396,408,420,432,444,456,468,480,492,504,516,528,540,552,564,576,588,600,612,624,636,648,660,672,684,696,708,720,732,744,756,768,780,792,804,816,828,840,852,864,876,888,900,912,924,936,948,960,972,984,996,1008,1020,1032,1044,1056,1068,1080,1092,1104,1116,1128,1140,1152,1164,1176,1188,1200,1212,1224,1236,1248,1260,1272,1284,1296,1308,1320,1332,1344,1356,1368,1380,1392,1404,1416,1428,1440,1452,1464,1476,1488,1500,1512,1524,1536,1548,1560,1572,1584,1596,1608,1620,1632,1644,1656,1668,1680,1692,1704,1716', 'vertex'),
    'Gamma_Top': ('vertex 11,23,35,47,59,71,83,95,107,119,131,143,155,167,179,191,203,215,227,239,251,263,275,287,299,311,323,335,347,359,371,383,395,407,419,431,443,455,467,479,491,503,515,527,539,551,563,575,587,599,611,623,635,647,659,671,683,695,707,719,731,743,755,767,779,791,803,815,827,839,851,863,875,887,899,911,923,935,947,959,971,983,995,1007,1019,1031,1043,1055,1067,1079,1091,1103,1115,1127,1139,1151,1163,1175,1187,1199,1211,1223,1235,1247,1259,1271,1283,1295,1307,1319,1331,1343,1355,1367,1379,1391,1403,1415,1427,1439,1451,1463,1475,1487,1499,1511,1523,1535,1547,1559,1571,1583,1595,1607,1619,1631,1643,1655,1667,1679,1691,1703,1715,1727', 'vertex'),
}

fields = {
    'temperature': ('real', 1, 'Omega', 1),
}

t0 = 0.0
t1 = 5000000000.0
num_steps = 1
dt = (t1 - t0) / num_steps

variables = {
    'T': ('unknown field', 'temperature', 0, 1),
    's': ('test field', 'temperature', 'T'),
}

_velocity_data = np.load(_velocity_npz_path)

def get_darcy_velocity_0(ts, coors, mode=None, problem=None, **kwargs):
    if mode != 'qp':
        return
    v_per_cell = _velocity_data['v0']  # (n_cells, 3), precomputed from stage 1
    n_qp = coors.shape[0] // v_per_cell.shape[0]
    v = np.repeat(v_per_cell, n_qp, axis=0)
    v = v.reshape(v.shape[0], v.shape[1], 1)
    return {'v': v}

def get_darcy_velocity_1(ts, coors, mode=None, problem=None, **kwargs):
    if mode != 'qp':
        return
    v_per_cell = _velocity_data['v1']  # (n_cells, 3), precomputed from stage 1
    n_qp = coors.shape[0] // v_per_cell.shape[0]
    v = np.repeat(v_per_cell, n_qp, axis=0)
    v = v.reshape(v.shape[0], v.shape[1], 1)
    return {'v': v}

def get_darcy_velocity_2(ts, coors, mode=None, problem=None, **kwargs):
    if mode != 'qp':
        return
    v_per_cell = _velocity_data['v2']  # (n_cells, 3), precomputed from stage 1
    n_qp = coors.shape[0] // v_per_cell.shape[0]
    v = np.repeat(v_per_cell, n_qp, axis=0)
    v = v.reshape(v.shape[0], v.shape[1], 1)
    return {'v': v}


def setup_precond(mtx, context):
    import scipy.sparse as sp
    import scipy.sparse.linalg as spla
    d = mtx.diagonal().copy()
    d[d == 0] = 1.0
    Dinv = sp.diags(1.0 / d)
    scaled = (Dinv @ mtx).tocsc()
    ilu = spla.spilu(scaled, drop_tol=1e-3, fill_factor=2)
    def solve(b):
        return ilu.solve(Dinv @ b)
    return spla.LinearOperator(mtx.shape, solve)

def ic_temp(coor, ic=None):
    # Exact linear interpolation between the enforced T_top/T_bottom EBCs
    # over the mesh's own actual z-extent (NOT a fixed geothermal-gradient
    # rate over the nominal domain height) -- mesh nodes are cell-centered,
    # inset from the nominal domain edges by half a cell on each side, so
    # using a fixed rate over the nominal height leaves a resolution-
    # dependent mismatch at the boundary that then diffuses through the
    # domain over time -- pure conduction (include_flow=False) should be
    # exactly static since this IC already is the steady-state solution.
    z_min, z_max = float(np.min(coor[:, 2])), float(np.max(coor[:, 2]))
    T_top, T_bottom = 10.0, 60.0
    return T_top + (T_bottom - T_top) * (z_max - coor[:, 2]) / (z_max - z_min)

functions = {
    'ic_temp': (ic_temp,),
    'get_darcy_velocity_0': (get_darcy_velocity_0,),
    'get_darcy_velocity_1': (get_darcy_velocity_1,),
    'get_darcy_velocity_2': (get_darcy_velocity_2,)
}

materials = {
    'm0': ({'k_eff': 2.215, 'rho_c_eff': 2497900.0},),
    'darcy0': 'get_darcy_velocity_0',
    'm1': ({'k_eff': 2.215, 'rho_c_eff': 2497900.0},),
    'darcy1': 'get_darcy_velocity_1',
    'm2': ({'k_eff': 2.215, 'rho_c_eff': 2497900.0},),
    'darcy2': 'get_darcy_velocity_2',
}

ics = {
    'ic': ('Omega', {'T.0': 'ic_temp'}),
}

ebcs = {
    'T_bottom': ('Gamma_Bottom', {'T.0': 60.0}),
    'T_top': ('Gamma_Top', {'T.0': 10.0}),
}

integrals = {
    'i': 1,
}

equations = {
    'heat': """dw_volume_dot.i.Omega0(m0.rho_c_eff, s, dT/dt)
  + dw_laplace.i.Omega0(m0.k_eff, s, T)
  + dw_advect_div_free.i.Omega0(darcy0.v, s, T)
  + dw_volume_dot.i.Omega1(m1.rho_c_eff, s, dT/dt)
  + dw_laplace.i.Omega1(m1.k_eff, s, T)
  + dw_advect_div_free.i.Omega1(darcy1.v, s, T)
  + dw_volume_dot.i.Omega2(m2.rho_c_eff, s, dT/dt)
  + dw_laplace.i.Omega2(m2.k_eff, s, T)
  + dw_advect_div_free.i.Omega2(darcy2.v, s, T)
  = 0""",
}

solvers = {
    'ls': ('ls.scipy_iterative', {
        'method': 'bicgstab',
        'i_max': 500,
        'eps_r': 1e-08,
        'setup_precond': setup_precond,
    }),
    'newton': ('nls.newton', {
        'i_max': 5,
        'eps_a': 1e-6,
        'is_linear': False,
        # report_status defaults to False in SfePy -- without it, the only
        # printed line per solve is the per-iteration residual (no
        # definitive "did this actually converge" signal). With it,
        # SfePy also prints a final "cond: N, iter: ..., err0: ..., err: ..."
        # line per solve (N: 0 = converged, 1 = max iterations reached
        # without converging, 2 = linesearch gave up) -- that's what
        # _run_sfepy_input_file()'s convergence check parses.
        'report_status': True,
    }),
    'ts': ('ts.simple', {
        't0': t0,
        't1': t1,
        'n_step': num_steps,
        'verbose': 1,
    }),
}

output_dir = os.environ.get("SFEpy_OUTPUT_DIR", "output")
os.makedirs(output_dir, exist_ok=True)

options = {
    'nls': 'newton',
    'ls': 'ls',
    'ts': 'ts',
    'save_times': 'all',
    'output_dir': output_dir,
}
