import unittest
import pickle
import gzip
import os

from core.object_components import MeshResults
from core.Simulation.Simulation_packages.Sfepy.simulation_run import run_sfepy


# =====================================================
# PICKLE LOADER
# =====================================================
class CustomUnpickler(pickle.Unpickler):
    def find_class(self, module, name):
        if name == "MeshResults":
            return MeshResults
        return super().find_class(module, name)


def load_pickle(path):
    if path.endswith(".gz"):
        with gzip.open(path, "rb") as f:
            return CustomUnpickler(f).load()
    else:
        with open(path, "rb") as f:
            return CustomUnpickler(f).load()


# =====================================================
# TEST CASE
# =====================================================
class SfepyFromPKLTestCase(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        base_dir = os.path.dirname(__file__)

        # -------------------------------------------------
        # INPUT FILE
        # -------------------------------------------------
        cls.input_file = os.path.join(
            base_dir,
            "Simulation_input_file",
            "Hydro_thermal.py"
        )

        # -------------------------------------------------
        # OUTPUT DIRECTORY
        # -------------------------------------------------
        cls.output_dir = os.path.join(base_dir, "sfepy_test_output")

        # -------------------------------------------------
        # MESH FROM PICKLE
        # -------------------------------------------------
        cls.pkl_file = os.path.join(base_dir, "mesh.pkl.gz")
        cls.mesh = load_pickle(cls.pkl_file)

        assert hasattr(cls.mesh, "nodes")
        assert hasattr(cls.mesh, "elements")

    def test_sfepy_runs_with_pkl_mesh(self):

        # -------------------------------------------------
        # FIXED CALL (NO KEYWORDS)
        # -------------------------------------------------
        result = run_sfepy(
            os.path.abspath(self.input_file),
            self.mesh,
            self.output_dir
        )

        # -------------------------------------------------
        # IMPORTANT: result is SfepySimulationOutput object
        # -------------------------------------------------
        self.assertTrue(os.path.exists(result.output_dir))

        # -------------------------------------------------
        # CHECK OUTPUT FILES
        # -------------------------------------------------
        files = []
        for root, _, f in os.walk(result.output_dir):
            files.extend(f)

        self.assertTrue(len(files) > 0, "No output files generated by SfePy")

        vtk_files = [f for f in files if f.endswith(".vtk") or f.endswith(".vtu")]
        self.assertTrue(len(vtk_files) > 0, "No VTK output found")

        print(f"[INFO] Simulation produced {len(vtk_files)} VTK files")


if __name__ == "__main__":
    unittest.main()
