import gzip
import os
import pickle
import tempfile
import unittest

from core.object_components import MeshResults
from core.simulation_components.simulation_packages.sfepy.simulation_run import run_sfepy


# =====================================================
# PICKLE LOADER
# =====================================================
class CustomUnpickler(pickle.Unpickler):
    def find_class(self, module, name):
        if name == "MeshResults":
            return MeshResults
        return super().find_class(module, name)


def load_pickle(path):
    if path.endswith(".gz"):
        with gzip.open(path, "rb") as f:
            return CustomUnpickler(f).load()
    else:
        with open(path, "rb") as f:
            return CustomUnpickler(f).load()


# =====================================================
# TEST CASE
# =====================================================
class SfepyFromPKLTestCase(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        base_dir = os.path.dirname(__file__)

        cls.input_file = os.path.join(
            base_dir,
            "simulation_input_file",
            "Hydro_thermal.py"
        )

        cls.pkl_file = os.path.join(base_dir, "mesh.pkl.gz")
        cls.mesh = load_pickle(cls.pkl_file)

        assert hasattr(cls.mesh, "nodes")
        assert hasattr(cls.mesh, "elements")

    def test_sfepy_runs_with_pkl_mesh(self):

        with tempfile.TemporaryDirectory() as tmp_output_dir:
            result = run_sfepy(
                os.path.abspath(self.input_file),
                self.mesh,
                tmp_output_dir
            )

            result_dir = result["output_dir"]

            self.assertTrue(os.path.exists(result_dir))

            files = []
            for root, _, f in os.walk(result_dir):
                files.extend(f)

            self.assertTrue(len(files) > 0, "No output files generated by SfePy")

            vtk_files = [f for f in files if f.endswith(".vtk") or f.endswith(".vtu")]
            self.assertTrue(len(vtk_files) > 0, "No VTK output found")

            print(f"[INFO] Simulation produced {len(vtk_files)} VTK files")


if __name__ == "__main__":
    unittest.main()
